# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:

- stage: docker_build
  jobs:
  - job:
    steps:
    - script: echo building

- stage: build_and_scan
  jobs:
  - job:
    steps:
    - task: SonarQubePrepare@5
      inputs:
        SonarQube: 'sonarqube'
        scannerMode: 'Other'
        extraProperties: |
          # Additional properties that will be passed to the scanner,
          # Put one key=value per line, example:
          # sonar.exclusions=**/*.bin
          sonar.projectKey=cicd_cicd
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        # remember to change dsonar.host.url with the vm's ip address
        # and dsonar.login with the generated token from sonarqube
        options: '-Dsonar.host.url=http://20.168.192.167:9000 -Dsonar.login=fb1e8f022b4e28e7ada4993364ff474d35c75d77'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: true
        sqMavenPluginVersionChoice: 'latest'
    - task: SonarQubePublish@5
      inputs:
        pollingTimeoutSec: '300'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)/s/target/simple-maven-war.war'
        artifact: 'simple-maven-war'
        publishLocation: 'pipeline'

- stage: deploy
  jobs:
  - job:
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'simple-maven-war'
        targetPath: '$(Pipeline.Workspace)/s'
    - task: TomcatDeployment@1
      inputs:
        TomcatUrl: 'http://20.168.192.167:8888'
        Username: 'admin'
        Password: '11'
        Warfile: 'simple-maven-war.war'
        Context: '/simple-maven-war'
        ServerVersion: '7OrAbove'
